### ISSUE TITLE
Creating rule set and child rule results in inconsistent remote state

### ISSUE THREAD

**Issue by kyongkim-illumio** [illumio/terraform-provider-illumio-core#15]
resource "illumio-core_pairing_profile" "terraform_pairing_profile_1" {
    name = "terraform_pairing_profile_1"
    enabled = true

    labels{
      href = illumio-core_label.terraform_app_label.href
    }

    labels{
      href = illumio-core_label.terraform_loc_label.href
    }

    labels{
      href = illumio-core_label.terraform_env_label.href
    }

    allowed_uses_per_key = "unlimited"
    key_lifespan = "50"
    env_label_lock = true
    loc_label_lock = true
    role_label_lock = false
    app_label_lock = true
    log_traffic = false
    log_traffic_lock = true
    enforcement_mode = "full"
    enforcement_mode_lock = true
    visibility_level = "flow_summary"
    visibility_level_lock = true
}

resource "illumio-core_security_rule" "terraform_postgres_rule" {
  rule_set_href = illumio-core_rule_set.terraform_rs1.href

  enabled = true

  resolve_labels_as {
    consumers = ["workloads"]
    providers = ["workloads"]
  }

  consumers {
    actors = "ams"
  }

  consumers {
    ip_list {
      href = illumio-core_ip_list.terraform_pce_ip_list.href
    }
  }

  consumers {
    workload {
      href = illumio-core_workload.terraform_workload_1.href
    }
  }

  ingress_services {
    href = illumio-core_service.terraform_postgres.href
  }

  providers {
    workload {
      href = illumio-core_workload.terraform_db0_pce.href
    }
  }

  providers {
    label {
      href = illumio-core_label.terraform_role_label.href
    }
  }
}

Results in ruleset and rule being created properly but subsequent apply results in

Terraform will perform the following actions:

  # illumio-core_rule_set.terraform_rs1 will be updated in-place
  ~ resource "illumio-core_rule_set" "terraform_rs1" {
        id          = "/orgs/1/sec_policy/draft/rule_sets/86"
        name        = "terraform-rs1"
        # (8 unchanged attributes hidden)

      - rules {
          - created_at         = "2021-06-18T05:31:02.310Z" -> null
          - created_by         = {
              - "href" = "/users/1"
            } -> null
          - deleted_by         = {} -> null
          - enabled            = true -> null
          - href               = "/orgs/1/sec_policy/draft/rule_sets/86/sec_rules/87" -> null
          - machine_auth       = false -> null
          - sec_connect        = false -> null
          - stateless          = false -> null
          - unscoped_consumers = false -> null
          - update_type        = "create" -> null
          - updated_at         = "2021-06-18T05:31:02.348Z" -> null
          - updated_by         = {
              - "href" = "/users/1"
            } -> null

          - consumers {
              - ip_list {
                  - href = "/orgs/1/sec_policy/draft/ip_lists/155" -> null
                }
            }
          - consumers {

              - workload {
                  - href = "/orgs/1/workloads/6b5849c8-76f8-48d7-9cb4-da1a07e22c47" -> null
                }
            }
          - consumers {
              - actors = "ams" -> null
            }

          - ingress_services {
              - href = "/orgs/1/sec_policy/draft/services/72" -> null
            }

          - providers {

              - label {
                  - href = "/orgs/1/labels/186" -> null
                }
            }
          - providers {

              - workload {
                  - href = "/orgs/1/workloads/d6819eee-532a-4f72-bb8d-f41efa876c17" -> null
                }
            }

          - resolve_labels_as {
              - consumers = [
                  - "workloads",
                ] -> null
              - providers = [
                  - "workloads",
                ] -> null
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

This is due to refresh of the rule_set state including the rule inline and terraform will delete the rule on subsequent apply. READ of rule_set needs to include ?representation=rule_set_scopes for consistency.

**Comment by dgajera-crest** [comment]
Hello @kyongkim-illumio , we are assigning these issue to our team and have started working on them. We will update here for any progress in resolving these issue.

**Comment by cmistry-crest** [comment]
@kyongkim-illumio  [PR#19](https://github.com/illumio/terraform-provider-illumio-core/pull/19) for this issue has been raised.
