### ISSUE TITLE
related pairing_profile and pairing_key fails on terraform destroy

### ISSUE THREAD

**Issue by kyongkim-illumio** [illumio/terraform-provider-illumio-core#16]
resource "illumio-core_pairing_profile" "terraform_pairing_profile_1" {
    name = "terraform_pairing_profile_1"
    enabled = true

    labels{
      href = illumio-core_label.terraform_app_label.href
    }

    labels{
      href = illumio-core_label.terraform_loc_label.href
    }

    labels{
      href = illumio-core_label.terraform_env_label.href
    }

    allowed_uses_per_key = "unlimited"
    key_lifespan = "50"
    env_label_lock = true
    loc_label_lock = true
    role_label_lock = false
    app_label_lock = true
    log_traffic = false
    log_traffic_lock = true
    enforcement_mode = "full"
    enforcement_mode_lock = true
    visibility_level = "flow_summary"
    visibility_level_lock = true
}

resource "illumio-core_pairing_keys" "terraform_pairing_key_1" {
    pairing_profile_href = illumio-core_pairing_profile.terraform_pairing_profile_1.href
    token_count = 3
}

running terraform destroy results in

Error: not-found: /orgs/1/pairing_profiles/33/pairing_keys

This is due to dependent deletion of pairing_keys pairing_profile. The provider needs to check to see if the key exists before delete.

**Comment by dgajera-crest** [comment]
Hello Kyong, we are assigning these issue to our team and have started working on them. We will update here for any progress in resolving these issue.

**Comment by dgajera-crest** [comment]
@kyongkim-illumio We were unable to reproduce this issue. We tried to destroy the resources multiple times but it gave consistent outputs of successful creation and destruction. 

Creation:
```
illumio-core_pairing_profile.terraform_pairing_profile_1: Creating...
illumio-core_pairing_profile.terraform_pairing_profile_1: Creation complete after 2s [id=/orgs/1/pairing_profiles/198]
illumio-core_pairing_keys.terraform_pairing_key_1: Creating...
illumio-core_pairing_keys.terraform_pairing_key_1: Creation complete after 1s [id=/orgs/1/pairing_profiles/198/pairing_keys]
```
Deletion:
```
illumio-core_pairing_keys.terraform_pairing_key_1: Destroying... [id=/orgs/1/pairing_profiles/198/pairing_keys]
illumio-core_pairing_keys.terraform_pairing_key_1: Destruction complete after 1s
illumio-core_pairing_profile.terraform_pairing_profile_1: Destroying... [id=/orgs/1/pairing_profiles/198]
illumio-core_pairing_profile.terraform_pairing_profile_1: Destruction complete after 1s

```
Can you please provide us TF files and if possible a video reference showing this error.

**Comment by kyongkim-illumio** [comment]
Deep, that issue is triggered by the UAT I had sent earlier. I'm wondering if it's more likely to occur with many resources being created simultaneously. Also, try creating more than 1 key associated with that profile. I'll send over the TF files I'm using to trigger that in an email.

**Comment by kyongkim-illumio** [comment]
Turns out this is a compatibility issue. Only the pre-21.2 PCE versions have this issue and those versions are not supported.
