### ISSUE TITLE
Error adding "enabled" to rule_set resource

### ISSUE THREAD

**Issue by vvaj** [illumio/terraform-provider-illumio-core#40]
Cannot disable a rule_set

Enable = false should disable the rule-set

Error on "terraform apply":

Error: not-acceptable:
│ Token: input_validation_error
│ Message: Input validation failed. Details: {The property '#/ip_tables_rules' of type null did not match the following type: array in schema sec_policy_rule_sets_put.schema.json}

## Steps to reproduce

resource "illumio-core_rule_set" "example" {
  description = "asdf"
  enabled     = false
  name        = "RS-TF-CORE-SERVICES-DEV"

  scopes {
    label {
      href = illumio-core_label.app_core_services.href
    }
     label {
      href = illumio-core_label.env_dev.href
    }
  }
}

**Comment by dsommerville-illumio** [comment]
This should be resolved with the latest changes. Bug introduced due to changes to the RuleSet model.
